name: Sync to S3

on:
  push:
    branches:
      - main
    paths:
      - 'systems.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1    
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
      - name: Sync systems.json
        run: |
          aws s3 sync . s3://archignes-search-systems --exclude '*' --include 'systems.json'
          aws s3 rm s3://archignes-search-systems/ --recursive --exclude 'systems.json'
